version: '3'

services:
  ansible:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ansible-cisco
    volumes:
      - .:/app
    working_dir: /app
    command: sleep infinity

  jenkins:
    build:
      context: .
      dockerfile: jenkins-ansible.Dockerfile
    user: root
    ports:
      - "8085:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
      - .:/var/jenkins_home/workspace/network-automation

volumes:
  jenkins_home: