apiVersion: apps/v1
kind: Deployment
metadata:
  name: cisco-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cisco-app
  template:
    metadata:
      labels:
        app: cisco-app
    spec:
      containers:
      - name: cisco-app
        image: python:3.10
        command: ["python3", "-m", "http.server", "8080"]
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: cisco-service
spec:
  type: NodePort
  selector:
    app: cisco-app
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30036
