- name: Configure Cisco Router (DevNet Sandbox)
  hosts: cisco
  gather_facts: no
  tasks:
    - name: Set Hostname
      ios_config:
        lines:
          - hostname DevNet-Automated

    - name: Configure Interface Description
      ios_config:
        lines:
          - description Managed by Ansible
        parents: interface GigabitEthernet2

    - name: Save Config
      ios_config:
        save_when: changed
